# Generated by Django 3.2 on 2022-05-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20220513_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='field',
        ),
        migrations.AddField(
            model_name='variant',
            name='field',
            field=models.ManyToManyField(to='inventory.VarientField'),
        ),
    ]
