# Generated by Django 4.0.3 on 2022-09-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_entry_ledger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='entry',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ledger',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledger',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=15),
            preserve_default=False,
        ),
    ]
