# Generated by Django 4.0.3 on 2022-09-26 12:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_alter_entry_options_entry_closing_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
