# Generated by Django 4.0.3 on 2022-10-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_entry_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='entries',
            field=models.ManyToManyField(blank=True, null=True, to='audit.entry'),
        ),
    ]
