# Generated by Django 4.0.3 on 2022-10-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_alter_ledger_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='entries',
            field=models.ManyToManyField(blank=True, to='audit.entry'),
        ),
    ]
