# Generated by Django 3.2 on 2022-06-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_organization_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='uuid',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='uuid',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
